service: dummy-test
frameworkVersion: ">=2.0.0"

provider:
  name: aws
  runtime: java8
  lambdaHashingVersion: 20201221
  region: ap-southeast-2
  stackTags:
    project: "dummy"
  endpointType: REGIONAL
  timeout: 5
  apiGateway:
    shouldStartNameWithService: true

resources:
  - ${file(res/aws-resources.yaml)}
  # - ${file(res/aws-web.yaml)}


package:
  artifact: target/hello-dev.jar

functions:
  hello:
    handler: com.serverless.Handler
    role: detailsFunctionRole
    timeout: 3
    memorySize: 2048
    events:
      - http:
          path: /form
          method: POST
          cors: true
          private: false